# Generated by Django 5.2.8 on 2025-11-13 13:53

import kenya.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenya', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file_name',
            new_name='original_filename',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='file_path',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='uploads/placeholder.txt', max_length=500, upload_to=kenya.models.user_file_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='upload_type',
            field=models.CharField(choices=[('portfolio', 'Portfolio Item'), ('job_file', 'Job File'), ('contract', 'Contract'), ('dispute_evidence', 'Dispute Evidence'), ('profile_picture', 'Profile Picture'), ('other', 'Other')], max_length=20),
        ),
    ]
